version: '2'
services:
    ekartshoppingapp-app:
        image: ekartshoppingapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ekartshoppingapp-postgresql:5432/ekartshoppingapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ekartshoppingapp-postgresql:
        extends:
            file: postgresql.yml
            service: ekartshoppingapp-postgresql
