version: '2'
services:
    ekartshoppingapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ekartshoppingapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ekartshoppingapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
